
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\Ticker\ticker.h"
#include "nlib\USonicEcho\USonicEcho.h"
#include "nlib\StringFormat\stringformat.h"
#include "nlib\StringSerial\stringserial.h"
#include "nlib\KernelPeriod\kernelperiod.h"
#include "nlib\OLEDisplay\OLEDisplay.h"

// -*-*- List of node objects -*-*-
nBlock_Ticker            nb_nBlockNode0_Ticker       (1000);
nBlock_USonicEcho        nb_nBlockNode1_USonicEcho   (p18, 58);
nBlock_StringFormat      nb_nBlockNode2_StringFormat ("Distance = %d cm\r");
nBlock_StringSerial      nb_nBlockNode3_StringSerial (USBTX, USBRX);
nBlock_KernelPeriod      nb_nBlockNode4_KernelPeriod (0.001);
nBlock_OLEDisplay        nb_nBlockNode5_OLEDisplay   (p9, p10, p27);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode2_StringFormat, 0,    &nb_nBlockNode3_StringSerial, 0);
nBlockConnection    n_conn1( &nb_nBlockNode2_StringFormat, 0,    &nb_nBlockNode5_OLEDisplay,   0);
nBlockConnection    n_conn2( &nb_nBlockNode1_USonicEcho,   0,    &nb_nBlockNode2_StringFormat, 0);
nBlockConnection    n_conn3( &nb_nBlockNode0_Ticker,       0,    &nb_nBlockNode1_USonicEcho,   0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
